openapi: 3.2.0
info:
  title: Acquia Cloud API Documentation Options API
  x-logo:
    url: assets/cloud-platform.svg
    backgroundColor: '#FFFFFF'
    altText: Acquia Cloud
  description: 'Acquia Cloud API


    # Compatibility


    ## Stability


    The response for all resource endpoints includes an `X-CloudAPI-Stability` header that indicates what changes, if any, Acquia will make to the resource and how changes will be communicated.'
  version: 2.0.0
  contact:
    name: Customer Experience Engineering (CXE)
    url: https://www.acquia.com
tags:
- name: Options
  x-displayName: Options
paths:
  /options:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Does not return any data. Allows traversal of options groups endpoints
      description: Does not return any data. Allows traversal of options groups endpoints.
      operationId: getOptions
      x-cli-name: options:list
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                properties:
                  _links:
                    $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
              example:
                _links:
                  self:
                    href: https://cloud.acquia.com/api/options
                  cde-sizes:
                    href: https://cloud.acquia.com/api/options/cde-sizes
                  log-forwarding:
                    href: https://cloud.acquia.com/api/options/log-forwarding
  /options/cde-sizes:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Displays the various CD Environment size options
      description: Displays the various CD Environment size options.
      operationId: getCdeSizes
      x-cli-name: options:cde-sizes-list
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_cde-sizes'
              example:
                total: 5
                _links:
                  self:
                    href: https://cloud.acquia.com/api/options/cde-sizes
                  parent:
                    href: https://cloud.acquia.com/api/options
                _embedded:
                  items:
                  - name: 1X
                    size: 1x
                    memory: 256
                    storage: 5
                    databases: 3
                    slots: 1
                  - name: 2X
                    size: 2x
                    memory: 512
                    storage: 10
                    databases: 6
                    slots: 2
                  - name: 3X
                    size: 3x
                    memory: 768
                    storage: 15
                    databases: 9
                    slots: 3
                  - name: 4X
                    size: 4x
                    memory: 1024
                    storage: 20
                    databases: 12
                    slots: 4
                  - name: 8X
                    size: 8x
                    memory: 2048
                    storage: 40
                    databases: 24
                    slots: 8
  /options/log-forwarding:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Does not return any data. Allows traversal of options groups endpoints
      description: Does not return any data. Allows traversal of options groups endpoints.
      operationId: getLogForwarding
      x-cli-name: options:log-forwarding
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                properties:
                  _links:
                    $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
              example:
                _links:
                  self:
                    href: https://cloud.acquia.com/api/options/log-forwarding
                  sources:
                    href: https://cloud.acquia.com/api/options/log-forwarding/sources
                  consumers:
                    href: https://cloud.acquia.com/api/options/log-forwarding/consumers
  /options/log-forwarding/sources:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Displays available log forwarding sources
      description: Displays available log forwarding sources.
      operationId: getLogForwardingSources
      x-cli-name: options:log-forwarding-source-list
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_log-forwarding-sources'
              example:
                total: 1
                _links:
                  self:
                    href: https://cloud.acquia.com/api/log-forwarding/sources
                  parent:
                    href: https://cloud.acquia.com/api/log-forwarding
                _embedded:
                  items:
                  - name: apache-access
                    label: Apache access
                    platforms:
                    - drupal
  /options/log-forwarding/consumers:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Displays available log forwarding consumers
      description: Displays available log forwarding consumers.
      operationId: getLogForwardingConsumers
      x-cli-name: options:log-forwarding-consumer-list
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_log-forwarding-consumers'
              example:
                total: 1
                _links:
                  self:
                    href: https://cloud.acquia.com/api/log-forwarding/consumers
                  parent:
                    href: https://cloud.acquia.com/api/log-forwarding
                _embedded:
                  items:
                  - name: sumologic
                    label: Sumologic
  /options/colors:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Options
      summary: Displays the various color options
      description: Displays the various color options.
      operationId: getColors
      x-cli-name: colors:list
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_colors'
              example:
                total: 10
                _links:
                  self:
                    href: https://cloud.acquia.com/api/options/colors
                  parent:
                    href: https://cloud.acquia.com/api/options
                  limit:
                    href: https://cloud.acquia.com/api/options/colors{?limit}
                    templated: true
                  offset:
                    href: https://cloud.acquia.com/api/options/colors{?offset}
                    templated: true
                  sort:
                    href: https://cloud.acquia.com/api/options/colors{?sort}
                    templated: true
                  filter:
                    href: https://cloud.acquia.com/api/options/colors{?filter}
                    templated: true
                _embedded:
                  items:
                  - color: blue
                  - color: blush
                  - color: gray
                  - color: green
                  - color: light-blue
                  - color: orange
                  - color: pink
                  - color: purple
                  - color: teal
                  - color: yellow
components:
  schemas:
    Acquia_Cloud_API_Documentation_color:
      type: object
      description: Response schema for a color.
      required:
      - color
      properties:
        color:
          type: string
          description: The color name.
    Acquia_Cloud_API_Documentation_log-forwarding-consumer:
      type: object
      description: Response schema for a Log forwarding consumer.
      required:
      - name
      - label
      properties:
        name:
          type: string
          description: The consumer name.
        label:
          type: string
          description: The consumer label.
    Acquia_Cloud_API_Documentation_cde-sizes:
      type: object
      required:
      - total
      - _links
      - _embedded
      properties:
        total:
          type: integer
          description: The number of items returned in the collection.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: The collection of CDE sizes.
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_cde-size'
    Acquia_Cloud_API_Documentation_log-forwarding-consumers:
      type: object
      required:
      - total
      - _links
      - _embedded
      properties:
        total:
          type: integer
          description: The number of items returned in the collection.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: The collection of Log forwarding consumers.
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_log-forwarding-consumer'
    Acquia_Cloud_API_Documentation_log-forwarding-sources:
      type: object
      required:
      - total
      - _links
      - _embedded
      properties:
        total:
          type: integer
          description: The number of items returned in the collection.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: The collection of Log forwarding sources.
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_log-forwarding-source'
    Acquia_Cloud_API_Documentation_colors:
      type: object
      required:
      - total
      - _links
      - _embedded
      properties:
        total:
          type: integer
          description: The number of items returned in the collection.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: The collection of colors.
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_color'
    Acquia_Cloud_API_Documentation_log-forwarding-source:
      type: object
      description: Response schema for a Log forwarding source.
      required:
      - name
      - label
      - platforms
      properties:
        name:
          type: string
          description: The source name.
        label:
          type: string
          description: The source label.
        platforms:
          type: array
          description: List of platforms for which the source is available.
          items:
            type: string
            description: The platform name.
    Acquia_Cloud_API_Documentation_cde-size:
      type: object
      description: Response schema for a CDE size.
      required:
      - name
      - size
      - memory
      - storage
      - databases
      - slots
      properties:
        name:
          type: string
          description: The CDE size name.
        size:
          type: string
          description: The CDE size.
        memory:
          type: integer
          description: The CDE memory in MB.
        storage:
          type: integer
          description: The CDE storage in GB.
        databases:
          type: integer
          description: Number of databases available.
        slots:
          type: integer
          description: Number of slots available.
    Acquia_Cloud_API_Documentation_links:
      type: object
      required:
      - self
      description: HAL links about the current resource.
      properties:
        self:
          type: object
          description: A link to this page.
          required:
          - href
          properties:
            href:
              type: string
              format: uri
              description: The URI for this page.
  securitySchemes:
    Acquia_Cloud_API_Documentation_OAuth2:
      type: oauth2
      description: 'All Cloud API calls need to be authenticated in order to work. You authenticate using a token that you can generate on your Acquia Profile page.


        ### To generate a token:


        1. Sign in to the [Acquia Cloud](https://cloud.acquia.com/) interface using your email address and Acquia password.

        2. Click your user avatar in the upper right corner, and then click **Account Settings**.

        3. On the Profile page, click **API Tokens**.

        4. Click **Create Token**.

        5. In the pop-up that appears, give your token a label so that you can easily find it later. Then click **Create Token**.

        6. Copy your API key and API secret. Click **OK**.

        '
      flows:
        clientCredentials:
          tokenUrl: https://accounts.acquia.com/api/token
          scopes: {}
    Codebase_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    MEO_Environment_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    Site_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
