openapi: 3.2.0
info:
  title: Acquia Cloud API Documentation Application Performance…
  x-logo:
    url: assets/cloud-platform.svg
    backgroundColor: '#FFFFFF'
    altText: Acquia Cloud
  description: 'Acquia Cloud API


    # Compatibility


    ## Stability


    The response for all resource endpoints includes an `X-CloudAPI-Stability` header that indicates what changes, if any, Acquia will make to the resource and how changes will be communicated.'
  version: 2.0.0
  contact:
    name: Customer Experience Engineering (CXE)
    url: https://www.acquia.com
tags:
- name: Application Performance Monitoring Services
  x-displayName: Application Performance Monitoring Services
paths:
  /environments/{environmentId}/settings/apm:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Application Performance Monitoring Services
      deprecated: true
      summary: Returns a list of Application Performance Monitoring services associated with…
      description: Returns a list of Application Performance Monitoring services associated with the environment.
      operationId: getEnvironmentsApmSetting
      x-cli-name: environments:apm-find
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_environment-id'
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_apm'
              example:
                type: newrelic
                key: 123456789abcdef037dea2e355bc43987a123456
                name: TestApplication
                flags:
                  enabled: true
                _links:
                  self:
                    href: https://cloud.acquia.com/api/environments/6-252031e4-59f0-7914-95a5-ff83699fdcde/settings/apm
                _embedded:
                  environment:
                  - _links:
                      self:
                        href: https://cloud.acquia.com/api/environments/6-252031e4-59f0-7914-95a5-ff83699fdcde
        '403':
          description: Forbidden
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not available:
                  value:
                    error: forbidden
                    message: APM settings are not available for this application.
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not found:
                  value:
                    error: not_found
                    message: The environment you are trying to access does not exist, or you do not have permission to access it.
                Not available on non-hosted applications:
                  value:
                    error: not_found
                    message: APM settings are not available on non-hosted applications.
    put:
      tags:
      - Application Performance Monitoring Services
      deprecated: true
      summary: Update configuration for an Application Performance Monitoring tool
      description: Update configuration for an Application Performance Monitoring tool.
      operationId: putEnvironmentsApmSetting
      x-cli-name: environments:apm-update
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_environment-id'
      requestBody:
        required: true
        content:
          application/hal+json:
            schema:
              type: object
              properties:
                status:
                  type: boolean
                  description: Whether the APM tool should be enabled or disabled. If updating an existing install, this value does not need to be provided.
                type:
                  type: string
                  description: The APM tool to install. Required if installing or updating a configuration.
                  enum:
                  - newrelic
                key:
                  type: string
                  description: The key for the APM tool. Required if installing or updating a configuration. This value should be available from your APM provider.
            example:
              type: newrelic
              key: Some New Relic key
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                status:
                  type: boolean
                  description: Whether the APM tool should be enabled or disabled. If updating an existing install, this value does not need to be provided.
                type:
                  type: string
                  description: The APM tool to install. Required if installing or updating a configuration.
                  enum:
                  - newrelic
                key:
                  type: string
                  description: The key for the APM tool. Required if installing or updating a configuration. This value should be available from your APM provider.
            example:
              type: newrelic
              key: Some New Relic key
      responses:
        '202':
          description: Accepted
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_message'
              examples:
                Settings are being updated:
                  value:
                    message: APM settings are being updated for this environment.
        '400':
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Validation failed:
                  value:
                    error: bad_request
                    message: APM names may only contain alphanumeric, dashes, dots, colons, underscores and space characters.
        '403':
          description: Forbidden
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Insufficient permissions:
                  value:
                    error: forbidden
                    message: You do not have permission to adjust APM settings for this environment.
                Acquia Cloud Free cannot modify:
                  value:
                    error: forbidden
                    message: Acquia Cloud Free accounts are not able to modify APM settings.
                Not available on non-hosted applications:
                  value:
                    error: forbidden
                    message: APM settings are not available on non-hosted applications.
                Hosted on Acquia Cloud Enterprise:
                  value:
                    error: forbidden
                    message: Please contact support to modify APM settings for this environment.
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not found:
                  value:
                    error: not_found
                    message: The environment you are trying to access does not exist, or you do not have permission to access it.
  /subscriptions/{subscriptionUuid}/apm:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Application Performance Monitoring Services
      summary: Returns a list of Application Performance Monitoring services associated with…
      description: Returns a list of Application Performance Monitoring services associated with the subscription.
      operationId: getSubscriptionApmTypes
      x-cli-name: subscriptions:apm-list
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_subscription-uuid'
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_apm-types'
              example:
                total: 1
                _links:
                  self:
                    href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm
                  parent:
                    href: https://cloud.acquia.com/api/subscriptions
                  sort:
                    href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm{?sort}
                    templated: true
                  filter:
                    href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm{?filter}
                    templated: true
                _embedded:
                  items:
                  - type: newrelic
                    flags:
                      opted-in: true
                    key: 2d1dfa83d5e1494793957e7ce572942b
                    _links:
                      self:
                        href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm/newrelic
                      parent:
                        href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm
        '403':
          description: Forbidden
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              example:
                error: forbidden
                message: You do not have permission to access APM summaries for this subscription.
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              example:
                error: not_found
                message: The subscription you are trying to access does not exist, or you do not have permission to access it.
  /subscriptions/{subscriptionUuid}/apm/{apmType}:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Application Performance Monitoring Services
      summary: Returns the Application Performance Monitoring service type associated with the…
      description: Returns the Application Performance Monitoring service type associated with the subscription.
      operationId: getSubscriptionApmType
      x-cli-name: subscriptions:apm-list
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_subscription-uuid'
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_apm-type'
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_apm-type'
              example:
                type: newrelic
                flags:
                  opted-in: true
                key: 2d1dfa83d5e1494793957e7ce572942b
                _links:
                  self:
                    href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a
                  parent:
                    href: https://cloud.acquia.com/api/subscriptions
        '403':
          description: Forbidden
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              example:
                error: forbidden
                message: You do not have permission to access this APM summary type.
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              example:
                error: not_found
                message: The subscription you are trying to access does not exist, or you do not have permission to access it.
  /subscriptions/{subscriptionUuid}/apm/{apmType}/actions/opt-in:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    post:
      tags:
      - Application Performance Monitoring Services
      summary: Enables New Relic Pro APM license for all applications on a subscription
      description: Enables New Relic Pro APM license for all applications on a subscription. This authorizes Acquia to create a new user account on the third-party New Relic platform using the name and e-mail address of the organization owner.
      operationId: postSubscriptionApmOptIn
      x-cli-name: subscriptions:apm-opt-in
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_subscription-uuid'
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_apm-type'
      security:
      - Acquia_Cloud_API_Documentation_OAuth2: []
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_message-with-links'
              examples:
                APM Type Enabled:
                  value:
                    message: APM type newrelic has been enabled on the example subscription.
                    _links:
                      self:
                        href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm/newrelic/actions/opt-in
                      parent:
                        href: https://cloud.acquia.com/api/subscriptions/8533debb-ae4e-427b-aa34-731719b4201a/apm/newrelic/actions
                      notification:
                        href: https://cloud.acquia.com/api/notifications/7b37b885-8ae4-454b-b8fa-ffaeff54f6a4
        '400':
          description: Bad Request
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_validation-error'
              examples:
                APM type unavailable:
                  value:
                    error: validation_failed
                    message:
                      name: New Relic is not available for this subscription.
                Must be organization owner:
                  value:
                    error: validation_failed
                    message:
                      name: Only the organization owner may opt into data sharing.
        '403':
          description: Forbidden
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Insufficient permissions:
                  value:
                    error: forbidden
                    message: You do not have permission to opt-in to APM settings for this subscription.
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not found:
                  value:
                    error: not_found
                    message: The subscription you are trying to access does not exist, or you do not have permission to access it.
components:
  parameters:
    Acquia_Cloud_API_Documentation_apm-type:
      name: apmType
      in: path
      required: true
      description: The APM type.
      schema:
        type: string
      example: newrelic
    Acquia_Cloud_API_Documentation_subscription-uuid:
      name: subscriptionUuid
      in: path
      description: The subscription entity's universally unique identifier.
      required: true
      schema:
        type: string
      example: 0f3ad33e-2fe4-11e9-b210-d663bd873d93
    Acquia_Cloud_API_Documentation_environment-id:
      name: environmentId
      in: path
      description: The environment identifier. The identifier is a compound key consisting of the internal database ID of the environment and the application UUID.
      required: true
      schema:
        type: string
      example: 12-d314739e-296f-11e9-b210-d663bd873d93
  schemas:
    Acquia_Cloud_API_Documentation_message:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          description: A simple message returned from the response.
    Acquia_Cloud_API_Documentation_error:
      type: object
      required:
      - error
      - message
      properties:
        error:
          type: string
          description: The error summary.
        message:
          type: string
          description: The long description for the returned error.
    Acquia_Cloud_API_Documentation_apm:
      type: object
      description: Details application performance monitor settings.
      required:
      - type
      - key
      - name
      - flags
      - _links
      - _embedded
      properties:
        type:
          type: string
          description: Indicates the APM type.
        key:
          type: string
          description: The APM license key.
        name:
          type: string
          description: The APM application name. New Relic only.
        flags:
          type: object
          description: An array of flags for an APM.
          properties:
            enabled:
              type: boolean
              description: Whether or not the APM is enabled.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: Entities related to the APM settings.
          properties:
            environment:
              type: array
              description: An array of links to related environments.
              items:
                type: object
                properties:
                  _links:
                    $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
    Acquia_Cloud_API_Documentation_message-with-links:
      type: object
      required:
      - message
      - _links
      properties:
        message:
          type: string
          description: The human-friendly confirmation of the creation of the resource.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
    Acquia_Cloud_API_Documentation_validation-error:
      type: object
      required:
      - error
      - message
      description: A validation error.
      properties:
        error:
          type: string
          description: The error summary.
        message:
          type: object
          description: The validation error message keyed by its field or group name.
          additionalProperties:
            type: string
    Acquia_Cloud_API_Documentation_apm-type:
      type: object
      required:
      - type
      - flags
      - key
      - _links
      properties:
        type:
          type: string
          description: The APM type.
          enum:
          - newrelic
        flags:
          type: object
          description: Additional APM information.
          properties:
            opted-in:
              type: boolean
              description: Whether the organization owner has opted into the APM type.
        key:
          type: string
          description: The APM license key.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
    Acquia_Cloud_API_Documentation_apm-types:
      type: object
      required:
      - total
      - _links
      - _embedded
      properties:
        total:
          type: integer
          description: The number of items returned in the collection.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          description: A collection of APM types matching the request parameters.
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_apm-type'
    Acquia_Cloud_API_Documentation_links:
      type: object
      required:
      - self
      description: HAL links about the current resource.
      properties:
        self:
          type: object
          description: A link to this page.
          required:
          - href
          properties:
            href:
              type: string
              format: uri
              description: The URI for this page.
  securitySchemes:
    Acquia_Cloud_API_Documentation_OAuth2:
      type: oauth2
      description: 'All Cloud API calls need to be authenticated in order to work. You authenticate using a token that you can generate on your Acquia Profile page.


        ### To generate a token:


        1. Sign in to the [Acquia Cloud](https://cloud.acquia.com/) interface using your email address and Acquia password.

        2. Click your user avatar in the upper right corner, and then click **Account Settings**.

        3. On the Profile page, click **API Tokens**.

        4. Click **Create Token**.

        5. In the pop-up that appears, give your token a label so that you can easily find it later. Then click **Create Token**.

        6. Copy your API key and API secret. Click **OK**.

        '
      flows:
        clientCredentials:
          tokenUrl: https://accounts.acquia.com/api/token
          scopes: {}
    Codebase_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    MEO_Environment_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    Site_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
