openapi: 3.2.0
info:
  title: Acquia Cloud API Documentation Cloud IDE API
  x-logo:
    url: assets/cloud-platform.svg
    backgroundColor: '#FFFFFF'
    altText: Acquia Cloud
  description: 'Acquia Cloud API


    # Compatibility


    ## Stability


    The response for all resource endpoints includes an `X-CloudAPI-Stability` header that indicates what changes, if any, Acquia will make to the resource and how changes will be communicated.'
  version: 2.0.0
  contact:
    name: Customer Experience Engineering (CXE)
    url: https://www.acquia.com
tags:
- name: Cloud IDE
  x-displayName: Cloud IDE
paths:
  /ides/{ideUuid}:
    servers:
    - url: https://cloud.acquia.com/api
      description: Cloud API
    get:
      tags:
      - Cloud IDE
      summary: Returns Cloud IDE info
      description: Returns Cloud IDE info.
      operationId: getIde
      x-cli-name: ide:find
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_ide-uuid'
      security:
      - Acquia_Cloud_API_Documentation_OAuth2: []
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_ide'
              example:
                uuid: 215824ff-272a-4a8c-9027-df32ed1d68a9
                label: Example IDE
                status: active
                _links:
                  self:
                    href: https://cloud.acquia.com/api/ides/215824ff-272a-4a8c-9027-df32ed1d68a9
                  parent:
                    href: https://cloud.acquia.com/api/ides
                  application:
                    href: https://cloud.acquia.com/api/applications/461fe350-7988-42b3-a73e-cffcdbb94199
                  web:
                    href: https://ide-215824ff-272a-4a8c-9027-df32ed1d68a9.prod.acquia-sites.com
                  ide:
                    href: https://215824ff-272a-4a8c-9027-df32ed1d68a9.ides.acquia.com
                _embedded:
                  owner:
                    uuid: 10be1d3e-f2b4-4d34-855d-321df3938ffd
                    first_name: First
                    last_name: Last
                    last_login_at: '2019-01-31T10:53:11-05:00'
                    created_at: '2016-08-14T17:38:59-04:00'
                    email: user.name@example.com
                    picture_url: https://accounts.acquia.com/path/to/image.png
                    username: user.name
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not found:
                  value:
                    error: not_found
                    message: The IDE you are trying to access does not exist, or you do not have permission to access it.
    delete:
      tags:
      - Cloud IDE
      summary: De-provisions a specific Cloud IDE
      description: De-provisions a specific Cloud IDE.
      operationId: deleteIde
      x-cli-name: ide:delete
      parameters:
      - $ref: '#/components/parameters/Acquia_Cloud_API_Documentation_ide-uuid'
      security:
      - Acquia_Cloud_API_Documentation_OAuth2: []
      responses:
        '202':
          description: Accepted
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_message-with-links'
              examples:
                De-provisioning IDE:
                  value:
                    message: The Cloud IDE is being deleted.
                    _links:
                      self:
                        href: https://cloud.acquia.com/api/ides/215824ff-272a-4a8c-9027-df32ed1d68a9
                      parent:
                        href: https://cloud.acquia.com/api/ides
                      notification:
                        href: https://cloud.acquia.com/api/notifications/e98577df-840a-4fef-8775-66cf90b3530e
        '404':
          description: Not Found
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_error'
              examples:
                Not found:
                  value:
                    error: not_found
                    message: The IDE you are trying to access does not exist, or you do not have permission to access it.
components:
  parameters:
    Acquia_Cloud_API_Documentation_ide-uuid:
      name: ideUuid
      in: path
      description: The Cloud IDE universally unique identifier.
      required: true
      schema:
        type: string
      example: da1c0a8e-ff69-45db-88fc-acd6d2affbb7
  schemas:
    Acquia_Cloud_API_Documentation_error:
      type: object
      required:
      - error
      - message
      properties:
        error:
          type: string
          description: The error summary.
        message:
          type: string
          description: The long description for the returned error.
    Acquia_Cloud_API_Documentation_user-profile:
      type: object
      description: A user profile.
      required:
      - uuid
      - first_name
      - last_name
      - last_login_at
      - created_at
      - email
      - picture_url
      - username
      properties:
        uuid:
          type: string
          format: uuid
          description: The user's UUID.
        first_name:
          type: string
          description: The user's first name.
        last_name:
          type: string
          description: The user's last name.
        last_login_at:
          deprecated: true
          type:
          - string
          - 'null'
          format: date-time
          description: The date/time of the last login for the user.
        created_at:
          type: string
          format: date-time
          description: The date the user was created.
        email:
          type: string
          format: email
          description: The user's email address.
        picture_url:
          type:
          - string
          - 'null'
          format: uri
          description: The URL for the user's picture.
        username:
          type: string
          description: The user's internal user name.
    Acquia_Cloud_API_Documentation_message-with-links:
      type: object
      required:
      - message
      - _links
      properties:
        message:
          type: string
          description: The human-friendly confirmation of the creation of the resource.
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
    Acquia_Cloud_API_Documentation_ide:
      type: object
      required:
      - uuid
      - label
      - status
      - _links
      properties:
        uuid:
          type: string
          format: uuid
          description: The unique identifier of the Cloud IDE.
        label:
          type: string
          description: The human-friendly label of the Cloud IDE.
        status:
          type: string
          description: The current provisioning status of the Cloud IDE.
          enum:
          - active
          - provisioning
          - deleting
          - updating
          - provision-failed
          - update-failed
          - delete-failed
        _links:
          $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_links'
        _embedded:
          type: object
          properties:
            owner:
              $ref: '#/components/schemas/Acquia_Cloud_API_Documentation_user-profile'
    Acquia_Cloud_API_Documentation_links:
      type: object
      required:
      - self
      description: HAL links about the current resource.
      properties:
        self:
          type: object
          description: A link to this page.
          required:
          - href
          properties:
            href:
              type: string
              format: uri
              description: The URI for this page.
  securitySchemes:
    Acquia_Cloud_API_Documentation_OAuth2:
      type: oauth2
      description: 'All Cloud API calls need to be authenticated in order to work. You authenticate using a token that you can generate on your Acquia Profile page.


        ### To generate a token:


        1. Sign in to the [Acquia Cloud](https://cloud.acquia.com/) interface using your email address and Acquia password.

        2. Click your user avatar in the upper right corner, and then click **Account Settings**.

        3. On the Profile page, click **API Tokens**.

        4. Click **Create Token**.

        5. In the pop-up that appears, give your token a label so that you can easily find it later. Then click **Create Token**.

        6. Copy your API key and API secret. Click **OK**.

        '
      flows:
        clientCredentials:
          tokenUrl: https://accounts.acquia.com/api/token
          scopes: {}
    Codebase_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    MEO_Environment_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
    Site_Service_JWT:
      type: apiKey
      description: Value for the Authorization header parameter.
      name: Authorization
      in: header
